### ISSUE TITLE
ICC profile has wrong copyright

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/png-hdr-pq#2]
The ICC profile states the wrong copyright - it should presumably assign copyright to W3C like the Note's copyright.

**Comment by palemieux** [comment]
Adobe has authorized W3C to distribute the profile from the W3C website, under the W3C Software and Document License. Please contact @wseltzer for details if needed.

**Comment by nigelmegitt** [comment]
@wseltzer I'm assuming you have had separate documentation from Adobe about this - please could you confirm this is fine for you, for the record?

**Comment by wseltzer** [comment]
Confirming that we've received the appropriate permission from Adobe.

**Comment by nigelmegitt** [comment]
Many thanks @wseltzer ! My mind is now slightly more at peace than it was 15 minutes ago...
