### ISSUE TITLE
ICC Profile link broken

### ISSUE THREAD

**Issue by beku** [w3c/png-hdr-pq#7]
The png-hdr-pq spec links to a ICC profile:
https://github.com/w3c/png-hdr-pq/blob/9ba20889d4b9335cebe65b979b788e9892c24370/index.html#L126
https://w3c.github.io/png-hdr-pq/icc/ITUR_2100_PQ_FULL.icc

...but the repository uses all upper case letters:
https://github.com/w3c/png-hdr-pq/blob/master/icc/ITUR_2100_PQ_FULL.ICC

Not sure if that's the reason why. Anyway, the link from the spec page is broken.

**Comment by palemieux** [comment]
It looks like Github Pages does not support `*.icc` . The document is officially published at https://www.w3.org/TR/png-hdr-pq/ , where the ICC link works.

@plehegar Can the link on the front page of the repo be changed from `https://w3c.github.io/png-hdr-pq/` to `https://www.w3.org/TR/png-hdr-pq/`?

**Comment by nigelmegitt** [comment]
I've made the change to the repo and opened #9 to add the ED link to the README instead.
